spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/ELearning
    username: postgres
    password: 2080
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

